score:
  image: registry.yandex-academy.ru/school/2024-06/backend/python/homeworks/hw3_dbindex/fruits/service-base:latest
  services:
  - name: registry.yandex-academy.ru/school/2024-06/backend/python/homeworks/hw3_dbindex/fruits/store:latest
    alias: store
  script:
  - cd src/
  - ls -la /
  - ls .
  - pytest -v --durations=0 
  artifacts:
    when: always
    reports:
      junit: src/report.xml
    paths:
      - score.json
